Fixes and some improvements phase 2
Cotecna-Inspection/cotecna-stencil pull request #6
Opened 2022-11-14 11:39 UTC by marcelpujol

2022-11-14 13:24 UTC, Xelit3 submitted a review, later dismissed
Approved mate @marcelpujol

2022-11-14 13:25 UTC, Xelit3 commented
This PR will not create a new package since no changes in package.json are done, is this corect @marcelpujol ?

2022-11-14 18:27 UTC, javierpardollama approved these changes

2022-11-14 18:27 UTC, javierpardollama commented on src/components/object-counter/object-counter.tsx
> +      ? this.field.value?.counted !== null || this.field.value?.image
Not sure about that Condition. Should not the folowing do the same?
```
return (this.field.value) ? this.field.value?.counted || this.field.value?.image;

2022-11-14 18:30 UTC, javierpardollama commented on src/components/object-counter/object-counter.tsx
> +    return (this.field.value)
Not sure about that Condition. Should not the folowing do the same?
```
return (this.field.value) ? this.field.value?.counted || this.field.value?.image;

2022-11-14 18:34 UTC, javierpardollama requested changes
Made some Comments. Can you check them please?

2022-11-16 13:08 UTC, marcelpujol commented
@javierpardollama To me it is correct, because in some cases the value could be filled without image entering the counted value in a manual way. We can do reflexion if you want, but to me it is clear as it is.

2022-11-16 13:11 UTC, javierpardollama approved these changes

2022-11-16 13:12 UTC, javierpardollama commented
> @javierpardollama To me it is correct, because in some cases the value could be filled without image entering the counted value in a manual way. We can do reflexion if you want, but to me it is clear as it is.

Perfect then. No more claims from my end. You got my approval

2022-11-16 13:27 UTC, RocioDelJ approved these changes

2022-11-16 14:11 UTC, merged